version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.4-alpine
    volumes:
      - ./data1:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=orcagov
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Brasil@@2026
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis-3,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"

networks:
  default:
    external: false

