version: '3.8'

services:
  orcagov-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orcagov-api
    restart: unless-stopped
    environment:
      - JWT_SECRET=ae19b8f7cbb744f0a45e90f21e0d4fbd7e35d452e0a18e3f782b3eac4a7d114c
      - JWT_EXPIRATION=604800000
    ports:
      - "8081:8080"
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - .:/app   # Monta tudo, incluindo pom.xml e mvnw

networks:
  default:
    external: false

